version: '3'
name: voxts-demo

services:
  voxts-demo:
    # profiles: [NOAUTO]
    build:
      dockerfile: packages/vox.ts/Dockerfile # relative to build context
      context: ./../..
    ports:
      - 33000:3000
    # deploy:
    #   replicas: 2
    # network_mode: host
    command:
      - bash
      - -uexc
      - cd /opt/voxscape/packages/vox.ts && exec yarn demo:run
    volumes:
      - ../ref-models:/opt/voxscape/packages/vox.ts/public/ref-models-2:ro
