name: Build preview docker images (x64 only)

on:
  workflow_call:
    inputs: {}
    # secrets: {}

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build-x64-image:
    name: Build docker image (x64)
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      # mostly taken from https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=pr
            type=sha

      - uses: docker/setup-buildx-action@v2

      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push to ghcr
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.docker/Dockerfile.web
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
