name: Build release multiarch images (arm64)

on:
  workflow_call: {}

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build-image:
    name: Build docker image
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: create temp image metadata
        run: |
          echo "image_name=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "image_tag=${GITHUB_SHA::9}" >> $GITHUB_ENV
      - name: build and push to ghcr
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.docker/Dockerfile.web
          platforms: linux/arm64
          push: true
          provenance: false
          sbom: false
          tags: ghcr.io/${{ env.image_name }}:${{ env.image_tag }}-arm64
          cache-from: type=gha,scope=voxscape-site-arm
          cache-to: type=gha,mode=max,scope=voxscape-site-arm
