name: Build release multiarch images (x64)

on:
  workflow_call: {}

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build-image-x64:
    name: Build docker image (x64)
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: create temp image metadata
        run: |
          echo "image_name=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "image_tag=${GITHUB_SHA::9}" >> $GITHUB_ENV
      - name: build and push to ghcr
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.docker/Dockerfile.web
          # platforms: linux/amd64
          platforms: linux/amd64
          push: true
          provenance: false
          sbom: false
          tags: ${{ env.image_name }}:${{ env.image_tag }}-x64
