name: Build release multiarch images (x64 / arm64)

on:
  # do not allow PR directly: see https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#hardening-for-self-hosted-runners
  workflow_call: {}
  push:
    tags:
    - "*"

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build-image-x64:
    name: Build docker image (x64)
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: create temp image metadata
        run: |
          echo "image_name=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "image_tag=${GITHUB_SHA::9}" >> $GITHUB_ENV
      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push to ghcr
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.docker/Dockerfile.web
          # platforms: linux/amd64
          platforms: linux/amd64
          push: true
          provenance: false
          sbom: false
          tags: |
            ghcr.io/${{ env.image_name }}:${{ env.image_tag }}-amd64

  build-image-arm64:
    name: Build docker image (arm64)
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: create temp image metadata
        run: |
          echo "image_name=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV # lowercase
          echo "image_tag=${GITHUB_SHA::9}" >> $GITHUB_ENV
      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push to ghcr
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.docker/Dockerfile.web
          platforms: linux/arm64
          push: true
          provenance: false
          sbom: false
          tags: |
            ghcr.io/${{ env.image_name }}:${{ env.image_tag }}-arm64
  # fuse-multiarch-image: TODO
  #   permissions:
  #     packages: write
  #   runs-on: ubuntu-22.04
  #   steps:
  #     # mostly taken from https://github.com/marketplace/actions/build-and-push-docker-images
  #     - name: Docker meta
  #       id: docker_meta
  #       uses: docker/metadata-action@v4
  #       with:
  #         images: ghcr.io/${{ github.repository }}
  #         tags: |
  #           type=ref,event=branch,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
  #           type=ref,event=pr
  #           type=sha

