name: Check code

on:
  workflow_call: {}

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  check-vox-ts:
    name: Check vox.ts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: 'yarn.lock'
      - run: yarn
      - run: yarn lint
        working-directory: ./packages/vox.ts/
      - run: yarn typecheck
        working-directory: ./packages/vox.ts/

  check-web:
    name: Check web
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: 'yarn.lock'
      - run: yarn
      - run: yarn prisma generate
        working-directory: ./web/
      - run: yarn lint
        working-directory: ./web/
      - run: yarn typecheck
        working-directory: ./web/
      - run: yarn build
        working-directory: ./web/
    # TODO: a stepto test server

