name: Check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - master
    - develop
  pull_request: {} # NOTE: worktree would be a temporal merge commit

jobs:
  check-code:
    uses: ./.github/workflows/check-code.yaml
  build-image:
    # needs: [check-code] # TODO: revert this
    uses: ./.github/workflows/build-image.yaml
