name: Check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - master
    - develop
  pull_request: {} # NOTE: worktree would be a temporal merge commit
    # paths: # NOTE: no idea how to use changed files to skip build-image step
    # - .docker
    # - .github/workflows

jobs:
  check-code:
    uses: ./.github/workflows/check-code.yaml
  build-image:
    needs: [check-code]
    if: github.event_name == 'push'
    uses: ./.github/workflows/build-image.yaml
